### ISSUE TITLE
0.29.1 Upgrade Guide

### ISSUE THREAD

**Issue by kedashoe** [ramda/ramda#3415]
[v0.29.0...v0.29.1](https://github.com/ramda/ramda/compare/v0.29.0...v0.29.1)

:boom: Breaking Changes:
None

:new: Added:
None

:bulb: Changes:
- #3376 Add empty path support for R.modifyPath
- #3394 make swap work when swapped items are arrays
- #3410 _curryN receive enough args

:star: Miscellaneous
- #3382 Add version to es distribution
- #3399 add sideEffects flag for es package.json

:clipboard: Documentation fixes: #3368 #3373 #3391 #3398 #3402

----------

Many thanks to all the contributors supporting this release.

We'd also like to call out to all those who submitted issues or PRs that we've chosen *not* to include.  It's often easy to forget that the attempts that fail are often just as important to long-term success as those that succeed.  Thank you for all your great work! :fireworks:

**Comment by tacomanator** [comment]
This says no breaking changes, but upgrading from 0.29.0 to 0.29.1, I'm getting type errors in my project related to `propEq()`. Is this just an out-of-date type in the types library, or is there an actual breaking change?

**Comment by kedashoe** [comment]
> looks like it was indeed a small difference in types

ty for the update. This is a good point though, it would be good to coordinate more carefully with the types when cutting releases going forward

**Comment by CrossEye** [comment]
This is great!  Thank you, @kedashoe !

**Comment by akshayjai1** [comment]
i am also getting 28 types errors
```
node_modules/types-ramda/es/index.d.ts:4453:22 - error TS1139: Type parameter declaration expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                          ~~~~~

node_modules/types-ramda/es/index.d.ts:4453:34 - error TS1005: ',' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                      ~~~~~~~

node_modules/types-ramda/es/index.d.ts:4453:51 - error TS1005: ',' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                       ~

node_modules/types-ramda/es/index.d.ts:4453:79 - error TS1005: ',' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                   ~

node_modules/types-ramda/es/index.d.ts:4453:82 - error TS1005: ',' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                      ~

node_modules/types-ramda/es/index.d.ts:4453:89 - error TS1005: ')' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                             ~

node_modules/types-ramda/es/index.d.ts:4453:91 - error TS1434: Unexpected keyword or identifier.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                               ~~~~~

node_modules/types-ramda/es/index.d.ts:4453:96 - error TS1128: Declaration or statement expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                    ~

node_modules/types-ramda/es/index.d.ts:4453:97 - error TS1128: Declaration or statement expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                     ~

node_modules/types-ramda/es/index.d.ts:4453:159 - error TS1005: ';' expected.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                                                                                   ~~~~~~~

node_modules/types-ramda/es/index.d.ts:4453:167 - error TS1434: Unexpected keyword or identifier.

4453 export function pick<const Names extends readonly [PropertyKey, ...PropertyKey[]]>(names: Names): <U extends Record<ElementOf<Names>, any>>(obj: U) => string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                                                                                           ~~~~~

node_modules/types-ramda/es/index.d.ts:4454:25 - error TS1139: Type parameter declaration expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                             ~~~~~

node_modules/types-ramda/es/index.d.ts:4454:37 - error TS1005: ',' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                         ~~~~~~~

node_modules/types-ramda/es/index.d.ts:4454:54 - error TS1005: ',' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                          ~

node_modules/types-ramda/es/index.d.ts:4454:61 - error TS1005: ',' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                 ~

node_modules/types-ramda/es/index.d.ts:4454:67 - error TS1003: Identifier expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                       ~

node_modules/types-ramda/es/index.d.ts:4454:74 - error TS1005: ')' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                              ~

node_modules/types-ramda/es/index.d.ts:4454:75 - error TS1128: Declaration or statement expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                               ~

node_modules/types-ramda/es/index.d.ts:4454:78 - error TS1005: ';' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                  ~

node_modules/types-ramda/es/index.d.ts:4454:79 - error TS1109: Expression expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                   ~

node_modules/types-ramda/es/index.d.ts:4454:86 - error TS1005: ')' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                          ~

node_modules/types-ramda/es/index.d.ts:4454:98 - error TS1005: ';' expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                      ~

node_modules/types-ramda/es/index.d.ts:4454:100 - error TS1434: Unexpected keyword or identifier.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                        ~

node_modules/types-ramda/es/index.d.ts:4454:101 - error TS1128: Declaration or statement expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                         ~

node_modules/types-ramda/es/index.d.ts:4454:102 - error TS1128: Declaration or statement expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                          ~

node_modules/types-ramda/es/index.d.ts:4454:104 - error TS1434: Unexpected keyword or identifier.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                            ~~~~~~

node_modules/types-ramda/es/index.d.ts:4454:111 - error TS1128: Declaration or statement expected.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                                   ~~~~~~~

node_modules/types-ramda/es/index.d.ts:4454:119 - error TS1434: Unexpected keyword or identifier.

4454 export function pick<U, const Names extends readonly [keyof U, ...(keyof U)[]]>(names: Names, obj: U): string extends keyof U ? Record<string, U[keyof U]> : Pick<U, ElementOf<Names>>;
                                                                                                                           ~~~~~


Found 28 errors in the same file, starting at: node_modules/types-ramda/es/index.d.ts:4453
```

**Comment by klepek42** [comment]
I'm getting the same 28 type errors in node_modules when updating from @types/ramda from 0.29.5 to 0.29.6.

**Comment by char0n** [comment]
I can confirm - getting reports of failed builds as well: https://github.com/swagger-api/swagger-js/issues/3176 (because of using ramda as transitive dep).

**Comment by char0n** [comment]
@akshayjai1, @klepek42 created a new discussion for the invalid typings at https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67032

**Comment by kedashoe** [comment]
@Harris-Miller any thoughts on this? I do not believe there were any related code changes, so I would guess people are seeing these issues simply because a new version of ramda resulted in people also getting the newest version of the types which had changes they were not expecting?

**Comment by Harris-Miller** [comment]
RE: type errors

Although we have brought maintaining the type definitions in-house with the [ramda/types](https://github.com/ramda/types) repo, they still are served through `@types/ramda`. For that reason, do understand that the types are not yet directly tied to the main lib and are still updated separately, and like any `@types/` definitions, it may take time to align the type definitions with changes made to the source lib.

It is something that I'll get on ASAP.

To address the main error brought up around `pick` in this thread. That is not directly related to `ramda@0.29.1` at all. It was part of this release last week: https://github.com/ramda/types/releases/tag/v0.29.5. That error only presents itself if you are using `typescript@<5`. We had marked `@types/ramda` that it requires `typescript@5` back for `0.29.0` (see here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts#L8) as to continue to best support the typings of ramda we needed latest syntax. It was only with the `types-ramda@0.29.5` update that typescript@5 syntax was introduced where users were seeing issues with still being on typescript@4.

Just update to `typescript@5`, and that issue will go away. If you cannot for some reason, you can force `npm` to use `types-ramda@0.29.4` by adding this to your `package.json`

```json
"overrides": {
    "types-ramda": "0.29.4"
}
```

This issue was brought up last week at `ramda/types` as well: https://github.com/ramda/types/issues/64

**Comment by Harris-Miller** [comment]
Changes from `0.29.1` and what needs to happen in `types-ramda`:
* https://github.com/ramda/ramda/pull/3376
  * Need to add type support for empty path
* https://github.com/ramda/ramda/pull/3394
  * No type updates needed
* https://github.com/ramda/ramda/pull/3410
  * This MR seems to handle an edge case that typescript prevents, nothing to be done
* https://github.com/ramda/ramda/pull/3382
  * Not code related
* https://github.com/ramda/ramda/pull/3399
 * Not code related

**Comment by Harris-Miller** [comment]
MR for modifyPath update: https://github.com/ramda/types/pull/68
