### ISSUE TITLE
R.adjust in Jest "TypeError: fn is not a function"

### ISSUE THREAD

**Issue by nicewaytodoit** [ramda/ramda#2912]
Literal just copied line from Ramda documentation:
```
    it('= R.adjust', () => {
        R.adjust(1, R.toUpper, ['a', 'b', 'c', 'd']);
    });
```
And I am getting :
```
  ● # Ramda › = R.adjust

    TypeError: fn is not a function

      24 | 
      25 |     it('= R.adjust', () => {
    > 26 |         R.adjust(1, R.toUpper, ['a', 'b', 'c', 'd']);
    at adjust (node_modules/ramda/src/adjust.js:39:17)
      at Object.adjust (node_modules/ramda/src/internal/_curry3.js:47:14)
      at Object.it (src/ramda.test.js:26:11)
```
Anyone why ?

**Comment by nicewaytodoit** [comment]
Sorry ll good version 0.25.0 has error, it works in 0.26.1

**Comment by shinynet** [comment]
This is still broken in 0.27.0

R.adjust(R.add(10), 1, [0, 1, 2]);  

TypeError: fn is not a function
    at adjust (/home/runner/PleasingFlawedUtility/node_modules/ramda/src/adjust.js:48:17)
    at Object.f3 [as adjust] (/home/runner/PleasingFlawedUtility/node_modules/ramda/src/internal/_curry3.js:55:14)
    at /home/runner/PleasingFlawedUtility/index.js:3:3
    at Script.runInContext (vm.js:131:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74

**Comment by Bradcomp** [comment]
@shinynet The first two arguments to `adjust` are flipped in your example. It should be 
`R.adjust(1, R.add(10), [0,1,2]);`

**Comment by shinynet** [comment]
You're right! I copied from a blog post. Should've looked at official docs. Thanks!
